DROP TABLE IF EXISTS MANAGERS;


CREATE TABLE MANAGERS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL
);


DROP TABLE IF EXISTS EMPLOYEES;
  
CREATE TABLE EMPLOYEES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL,
  city VARCHAR(250) DEFAULT NULL,
  manager_id INT NOT NULL,
  CONSTRAINT `FK_Manager` FOREIGN KEY (`manager_id`) REFERENCES `MANAGERS` (`id`)
);



